### PR TITLE
drop tablewriter dependency

### LINKED ISSUE #286: print.go fails to compile with tablewriter v1.0.7 due to removed constants and methods
**Description:**

When using [`github.com/olekukonko/tablewriter v1.0.7`](https://github.com/olekukonko/tablewriter) with this library, `print.go` fails to compile due to multiple undefined constants and missing method definitions. This seems to be caused by changes in `tablewriter` removing alignment constants like `ALIGN_LEFT` and several methods on `tablewriter.Table`.

Here’s the full list of compilation errors encountered with `parquet-go v0.25.0` and `tablewriter v1.0.7`:

```
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:228:31: undefined: tablewriter.ALIGN_LEFT
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:230:31: undefined: tablewriter.ALIGN_RIGHT
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:256:43: undefined: tablewriter.ALIGN_LEFT
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:271:5: tw.SetAutoFormatHeaders undefined (type *tablewriter.Table has no field or method SetAutoFormatHeaders)
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:272:5: tw.SetColumnAlignment undefined (type *tablewriter.Table has no field or method SetColumnAlignment)
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:273:5: tw.SetHeaderAlignment undefined (type *tablewriter.Table has no field or method SetHeaderAlignment)
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:273:36: undefined: tablewriter.ALIGN_LEFT
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:274:5: tw.SetFooterAlignment undefined (type *tablewriter.Table has no field or method SetFooterAlignment)
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:274:36: undefined: tablewriter.ALIGN_LEFT
../../go/pkg/mod/github.com/parquet-go/parquet-go@v0.25.0/print.go:275:5: tw.SetHeader undefined (type *tablewriter.Table has no field or method SetHeader)
```

This appears in `tablewriter` version `v1.0.7`. A potential solution could be to either:
- Pin a compatible version (prior to v1.0.7), or
- Refactor the code in `print.go` to work with the updated `tablewriter` API.

---

**Steps to Reproduce:**

1. Use the following in your `go.mod`:

   ```go
   require (
       github.com/parquet-go/parquet-go v0.25.0
       github.com/olekukonko/tablewriter v1.0.7
   )
   ```

2. Run `go build`

---

**Expected behavior:**

`print.go` should compile cleanly with `tablewriter v1.0.7`.

---

**Suggested Fix:**

- Update `print.go` to reflect API changes in `tablewriter v1.0.7`, or
- Pin the dependency to an earlier compatible version in `go.mod`.

### PR DESCRIPTION
**Pull request by achille-roussel**
Fixes #286

Quality of life improvement: use Claude Code to generate replacements for open-source dependencies that introduced breaking changes.

### CODE REVIEW

**Comment by achille-roussel** [comment]
Merging to unbreak users.
