### PR TITLE
Add support to write Parquet files with NULL type columns (#517)

### LINKED ISSUE #517: Writing parquet files with NULL-type columns is not supported
Since v0.26 (fix for #151), parquet-go can **read** parquet files containing columns with `UNKNOWN (always null)` logical type — all values are correctly returned as `null`. However, **writing** a parquet file that preserves these NULL-type columns still fails because `nullType` does not implement `NewColumnBuffer()`.

## Context

Pyarrow (Python) generates parquet files where columns filled entirely with `NULL` values use:
- **Physical type**: `INT32`
- **Logical type**: `UNKNOWN (always null)`

This is valid per the [Parquet specification](https://github.com/apache/parquet-format/blob/master/LogicalTypes.md#unknown-always-null). When such a file is read with parquet-go, the library correctly maps these columns to its internal `nullType` (introduced in #151).

The use case is a streaming mask pipeline that reads a parquet file row-by-row, transforms some values, and writes the result to a new parquet file using the **original schema** (including NULL-type columns preserved as-is).

### 1. Create a test parquet file with NULL columns (Python)

```python
import pyarrow as pa
import pyarrow.parquet as pq

# A column entirely filled with NULLs — pyarrow assigns logical type UNKNOWN
null_col = pa.array([None, None, None], type=pa.null())
normal_col = pa.array(["alice", "bob", "charlie"])

table = pa.table({
    "name": normal_col,
    "all_nulls": null_col,
})

pq.write_table(table, "test_with_null_column.parquet")
```

### 2. Read + write with the original schema (Go)

```go
package main

import (
	"os"

	"github.com/parquet-go/parquet-go"
)

func main() {
	f, _ := os.Open("test_with_null_column.parquet")
	defer f.Close()

	stat, _ := f.Stat()
	reader := parquet.NewReader(f, parquet.FileSize(stat.Size()))
	defer reader.Close()

	// Reading works fine since v0.26
	schema := reader.Schema()

	// Writing with the same schema panics
	out, _ := os.Create("output.parquet")
	defer out.Close()

	writer := parquet.NewWriter(out, schema) // panic: cannot create buffer for values of type <null>
	defer writer.Close()

	for {
		row := make(map[string]any)
		if err := reader.Read(&row); err != nil {
			break
		}
		writer.Write(row)
	}

	writer.Close()
}
```

### Expected behavior

The writer should handle NULL-type columns by writing them as all-null values (definition levels = 0, no data pages), preserving the column in the output schema.

### Actual behavior

`NULL column types are not supported by parquet writer` when `parquet.NewWriter` is called with a schema containing NULL-type columns.

## Environment

- parquet-go: v0.29.0
- Go: 1.24
- OS: Linux (reproducible on any platform)

## Workaround

We currently work around this by patching the Thrift-encoded parquet footer in-memory before opening the writer: we strip the `LogicalType.Unknown` annotation from NULL-type `SchemaElement` entries and set the physical type to `INT32`. This forces parquet-go to treat these columns as regular `INT32` columns (with all values being `null`), which the writer can handle.

This workaround is effective but not ideal — it modifies the schema semantics and requires manual Thrift footer manipulation.

### PR DESCRIPTION
**Pull request by airKlizz**
The PR fixes #517 by adding support to write Parquet files with NULL logical type columns.

Changes:

- Adds nullColumnBuffer implementing the ColumnBuffer interface for NULL columns
- Adds nullColumnIndexer implementing the ColumnIndexer interface for NULL columns
- Implements NewColumnBuffer, NewColumnIndexer on nullType to return working instances
- Sets PhysicalType() to INT32 and ColumnOrder() to type-defined order (following pyarrow spec)
- Exports NullType variable for external use
- Adds test coverage for writing files with NULL columns

### CODE REVIEW

**Review by achille-roussel — APPROVED** [review]
This looks great, thanks for your contribution!

**Comment by bench** [comment]
Very cool ! 
Can we expect a new release soon @achille-roussel  ?
TYVM.

**Comment by achille-roussel** [comment]
Here you go https://github.com/parquet-go/parquet-go/releases/tag/v0.30.0
